version: "3"

services:
  todo-app:
    container_name: todo-app
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - go-app-network
    command: tail -f /dev/null
    volumes:
      - ./.:/go/src/github.com/forgoty/go-todo

networks:
  go-app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.53.0/24
